name: GitOps Enterprise

on:
  pull_request:

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: self-hosted

    environment: production

    steps:

    - uses: actions/checkout@v3

    - name: Configure AWS Credentials (OIDC)
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: arn:aws:iam::005104643423:role/GitHubActionsRole
        aws-region: us-west-2

    - name: Terraform Init
      run: terraform init
      working-directory: terraform

    - name: Terraform Plan
      run: |
        terraform plan -out=tfplan
        terraform show tfplan > tf.txt
      working-directory: terraform

    - name: RFC IA
      run: |
        cp terraform/tf.txt .
        python3 scripts/generate_rfc.py

    - name: Mostrar RFC
      run: cat RFC.md

    - name: Terraform Apply
      run: terraform apply -auto-approve
      working-directory: terraform

    - name: Ansible
      run: |
        ansible-playbook ansible/playbook.yml \
        -i ansible/inventory.yml