name: GitOps PoC

on:
  #pull_request:
  push:
    branches: [ "**"]

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: self-hosted
    environment: production

    steps:

    - uses: actions/checkout@v3

    - name: Configure AWS (OIDC)
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: arn:aws:iam::005104643423:role/GitHubActionsRole
        aws-region: us-east-1

    - name: Terraform Init
      run: terraform init
      working-directory: gitops/terraform

    - name: Terraform Plan
      run: |
        terraform plan -out=tfplan
        terraform show tfplan > tf.txt
      working-directory: gitops/terraform

    - name: Generate RFC (IA)
      run: |
        cp gitops/terraform/tf.txt . || echo "tf.txt no existe en terraform/"
        python3 gitops/scripts/generate_rfc.py

    - name: Send RFC to Teams
      env:
        WEBHOOK_TEAMS: ${{ secrets.WEBHOOK_TEAMS }}
      run: |
        curl -H "Content-Type: application/json" \
        -d "{\"text\":\"$(cat RFC.md | sed ':a;N;$!ba;s/\n/\\n/g')\"}" \
        "$WEBHOOK_TEAMS"

    - name: Show RFC
      run: cat RFC.md

    - name: Terraform Apply
      run: terraform apply -auto-approve
      working-directory: gitops/terraform

    - name: Ansible Deploy
      run: |
        ansible-playbook gitops/ansible/playbook.yml \
        -i ansible/inventory.yml